image: node:latest
stages:
  - deploy

deploy:
  tags:
    - sdk
  stage: deploy
  environment: develop
  only:
    - feature/deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - NPM_TOKEN=${NPM_TOKEN} npm publish