image: node:latest
stages:
  - deploy

deploy:
  tags:
    - sdk
  stage: deploy
  environment: develop
  only:
    - develop
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm install
    - npm run build
    - NPM_TOKEN=${NPM_TOKEN} npm publish